### ISSUE TITLE
about output from one of your problems 

### ISSUE THREAD

**Issue by nasser1** [EleutherAI/math-lm#79]
at https://llemma-demo.github.io/  under intermediate algebra, problem 3 you show this:

![image](https://github.com/EleutherAI/math-lm/assets/15114517/9b5dccee-f534-461a-9a0f-cd3fb40da5ac)

Final answer is correct which is 1/2, but going to 1/(k! (k+2))  to  1/(k+2)!   can not be possible because 1/(k+2)! does not give 1/2.  So how did this step come into play?  I checked using Mathematica:

![image](https://github.com/EleutherAI/math-lm/assets/15114517/2ce257ef-0b88-482d-8344-6ee967f31da8)

**Comment by zhangir-azerbayev** [comment]
In order for automatic scoring to be possible, we only evaluate the correctness of the final answer, not the chain-of-thought. 

From a probabilistic perspective this is well motivated, because it's equivalent to marginalizing over all the latent chains-of-thought, but from a "we want the model's reasoning to be correct" perspective it's obviously unfortunate.
