### ISSUE TITLE
ProofNet Autoformalization (Eval Task)

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/math-lm#9]

**Comment by wellecks** [comment]
I'll take this one 👍

**Comment by wellecks** [comment]
Some examples with `pythia-1.4b-deduped`: 

Informalization:
<img width="1323" alt="" src="https://user-images.githubusercontent.com/680489/225777868-5481205d-e9fe-4d49-865b-9cdf3e8b189f.png">

Formalization:
<img width="1314" alt="" src="https://user-images.githubusercontent.com/680489/225777896-ae44bac6-50e1-4bd1-aa6e-7122a04d75eb.png">

**Comment by wellecks** [comment]
A couple notes:
1. We are using randomly sampled examples in the few-shot prompt (standard in the LM harness), instead of a fixed prompt like in the paper. In terms of the prompt content, one difference is that the name of each theorem is `exercise_{X}_{Y}_{Z}` in the examples, versus a 'more semantic' name in the paper's prompt (e.g. `linear_independent_of_is_Ortho`).
2. It's computing BLEU score on tokenized sequences, using the galactica tokenizer. Of course, there is still no guarantee of a correlation with correctness, but perhaps it is less noisy than computing BLEU on whitespace-tokenized sequences. We could also take this out. I'll see if BLEU score at least shows the ordering that we expect with increased scale.

**Comment by zhangir-azerbayev** [comment]
I am currently working on a Lean 4 version of ProofNet. Because there now exist [Python bindings for Lean 4](https://github.com/zhangir-azerbayev/repl), we will be able to automatically evaluate typechecking from our harness fork. 

Correctness will still have to be checked manually.

**Comment by wellecks** [comment]
For informalization, added an experimental gpt-based correctness evaluation (https://github.com/wellecks/lm-evaluation-harness/pull/4).

**Comment by zhangir-azerbayev** [comment]
Solved by wellecks/lm-evaluation-harness#4
